# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
        ('home', '0003_layout'),
    ]

    operations = [
    ]
