# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20180206_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Layout',
        ),
    ]
